image: ubuntu:latest
stages:
  - lint
  - build

lint:
  stage: lint
  script:
    - ssh-keyscan -t rsa gitlab.jonathan-martz.de >> ~/.ssh/known_hosts
    - sudo rm -rf /tmp/pocketstore.io
    - git clone git@gitlab.jonathan-martz.de:softwareentwicklung/nuxt-pocketstore.git /tmp/pocketstore.io
    - cd /tmp/pocketstore.io
    - bun install
build:
  stage: build
  script:
    - ssh-keyscan -t rsa gitlab.jonathan-martz.de >> ~/.ssh/known_hosts
    - cd /tmp/pocketstore.io
    - bun run build
    - ssh root@pocketstore.io 'cd /var/www/nuxt && rm -rf .output'
    - scp -r .output root@pocketstore.io:/var/www/nuxt
    - scp ecosystem.config.cjs root@pocketstore.io:/var/www/nuxt/.
    - ssh root@pocketstore.io 'cd /var/www/nuxt && bun x pm2 restart ecosystem.config.cjs'