name: SSH Deploy

on:
  push:
    branches:
      - main  # Run on pushes to the main branch; adjust as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH and Run Commands
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: "root"  
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: | 
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash && \
            source ~/.bashrc && \
            nvm install --lts && \
            npm install -g bun pm2 && \
            bun install && \
            bun run build && \